name: Payall_by_Aleondev
api:
- 3.0.0
- 4.0.0
version: 1_CoreGames
main: Aleondev\payall\Main
author:
- Aleondev
- CoreGames.nbb.one
load: STARTUP
commands:
  payall:
    description: §4Payall §bBy Aleondev
    usage: "/payall"
    permission: payall.command
    default: true
